name: Deploy Zenith Solve rBackend Changes to DigitalOcean Server

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Setup SSH key for server access
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DO_SERVER_SSH_KEY }}
    
    # Deploy to server using SSH
    - name: Deploy to DigitalOcean
      env:
        SERVER_IP: ${{ secrets.DO_SERVER_IP }}
        SERVER_USER: ${{ secrets.DO_SERVER_USER }}
        SERVER_PORT: ${{ secrets.DO_SERVER_PORT }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
        
        # Complex SSH command with error handling and Slack notifications
        ssh $SERVER_USER@$SERVER_IP -p $SERVER_PORT << EOF
          # Navigate to scripts directory
          cd scripts

          # Execute deployment script
          sh deploy-zenith-backend.sh

          # Check if the deployment was successful
          if [ $? -eq 0 ]; then
            echo "Deployment successful"
            exit 0
          else
            echo "Deployment failed"
            exit 1
          fi
        EOF
      
    # Slack notification for successful deployment
    - name: Slack Notification on Success
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        custom_payload: |
          {
            "attachments": [{
              "color": "good",
              "text": "✅ Deployment Successful! \nBranch: ${{ github.ref_name }}\nCommit: ${{ github.sha }}"
            }]
          }
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    # Slack notification for deployment failure
    - name: Slack Notification on Failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        custom_payload: |
          {
            "attachments": [{
              "color": "danger",
              "text": "❌ Deployment Failed! \nBranch: ${{ github.ref_name }}\nCommit: ${{ github.sha }}"
            }]
          }
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}